### ISSUE TITLE
I’m unable to save the maps API key

### ISSUE THREAD

**Issue by raulmarinperez** [egeoffrey/egeoffrey-gui#11]
**Describe the bug**
As admin user I'm trying to save the Maps API key but nothing happens and the value is not kept in the system.

**Version**
1.0-72 (master)

**To Reproduce**
1. Log into egeoffrey as admin user
2. From the menu side bar: Administration -> House -> Settings
3. From the House settings screen, go to the Web Interface tab
4. Paste a valida Map API key and click the Save button.
5. Nothing happens. No notification. If you move to other section in egeoffrey and come back to the same screen, they value provided is gone.

**Screenshots**
**1. Opening the house settings screen**
<img width="716" alt="1  Opening the house settings screen" src="https://user-images.githubusercontent.com/15977445/70438040-3deeea00-1a8d-11ea-93e3-fdc497035c39.png">
**2. Go to the web interface tab**
<img width="1000" alt="2  Go to the web interface tab" src="https://user-images.githubusercontent.com/15977445/70438041-3deeea00-1a8d-11ea-9f1d-e8dd401d0fb7.png">
**3. Paste a valid key (no longer valid as it's removed)**
<img width="894" alt="3  Paste a valid key" src="https://user-images.githubusercontent.com/15977445/70438044-3e878080-1a8d-11ea-82e5-a87d708b30ef.png">
**4. Page refreshed and they key is gone**
<img width="888" alt="4  Page refreshed and they key is gone" src="https://user-images.githubusercontent.com/15977445/70438045-3e878080-1a8d-11ea-9b76-b8e5f48179d7.png">

**Comment by user2684** [comment]
button was wrongly referencing _house_save instead of _gui_save
