### ISSUE TITLE
"Show more" links in the main screen (Alerts, Warnings, Informational) takes you to the top

### ISSUE THREAD

**Issue by raulmarinperez** [egeoffrey/egeoffrey-gui#12]
**Describe the bug**
"Show more" links in the main screen (Alerts, Warnings, Informational) takes you to the top rather to the notifications screen filtered by the chosen category.

**Version**
1.0-72 (master)

**To Reproduce**
1. From the main screen "Notifications and rules" section, scroll down a little up until you see the three boxes.
2. Click on any of the "Show more" links.
3. You're taken to the top

**Screenshots**
**The three boxes**
<img width="1095" alt="The three boxes" src="https://user-images.githubusercontent.com/15977445/70438665-98d51100-1a8e-11ea-898b-5ab5bb16386d.png">

**Comment by user2684** [comment]
the old overview/notifications was referenced, fixed
