### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by raulmarinperez** [egeoffrey/egeoffrey-gui#14]
**Describe the bug**
I created a user who is no longer valid and I'm unable to remove it from the system. When I'm in the right place to remove the user and I hit the "Delete User" button, nothing happens and the form adds new fields.

**Version**
1.0-72 (master)

**To Reproduce**
1. Log into egeoffrey as admin user
2. From the menu side bar: Administration -> House -> Settings
3. From the House settings screen, go to the Users tab
4. Choose the use you want to remove and click the "Delete User" button
5. No notification about the deletion and new fields in the form are included (with other usernames and stuff)

**Screenshots**
**1. Delete User button doesn't delete**
<img width="1343" alt="1  Delete User button doesn't delete" src="https://user-images.githubusercontent.com/15977445/70445002-169f1980-1a9b-11ea-9af6-2715de8a15e4.png">
**2. Corrupted form**
<img width="1340" alt="2  Corrupted form" src="https://user-images.githubusercontent.com/15977445/70445003-169f1980-1a9b-11ea-9649-3cd65b22374d.png">

**Comment by user2684** [comment]
Variable wrongly referenced, fixed
