### ISSUE TITLE
History data not accessible

### ISSUE THREAD

**Issue by eporocrail** [egeoffrey/egeoffrey-gui#84]
In the time chart widget it should be possible to select a period and get data of that period. In no way I m able to get any data from the past.

![history](https://user-images.githubusercontent.com/19239290/99945213-84a82380-2d74-11eb-8fd4-c85c9f667be7.jpg)

**Comment by user2684** [comment]
Couple of things to check first:
* Which is the retention configured for the sensors?
* If you go to "eGeoffrey" "Database", when the oldest data for the sensor is dated? 
Just to ensure we really have the history for those sensors.
Thanks

**Comment by eporocrail** [comment]
All set to "history".
When I select a sensor and request the history I get under "daily timeline" data for three months. I suppose that that should do.
I can not access the data in the Redis database.

**Comment by eporocrail** [comment]
I did look into the issue a little deeper.
I have four temperature sensors.
Looking at the history of each sensor I made the following observations:
Three displays: timeline, hourly and daily. In general only the daily timeline could zoom in. The others not.
Three out of four loaded the data OK. One did load "timeline" and "hourly". The "daily" kept loading.
The other three showed all data. But as stated only the "daily" can be zoomed. 

To do the evaluation had to create new timeline widgets. Where I have some more eGeoffrey sensors in the system the performance crating new widgets is decreasing very much.
After clicking the add button it takes several seconds for the pop-up window "loading" to appear. Then again it takes again several seconds seconds to come up with the widget.

Another amazing observation:
After creating one widget I could not edit this one via the GUI. The edit button was not shown.
After having made two other ones I saw that all of them had the edit button.

I will look into this phenomenon also.

**Comment by user2684** [comment]
Mmm, the behaviour still sounds expected to me. The daily measures only are kept for a longer timespan than the one presented in the widget, the others are purged according to the retention policies. 
Still a look at the database could help here. You don't need to access it directly, just go to "eGeoffrey" / "Database from the gui and search for your sensor. You should see "day" and "hour" suffix storing avg, min and max, with the timestamp of the oldest and newest measure for each

**Comment by eporocrail** [comment]
Here is the content of the database:

eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/bme/day/avg	1	158 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/bme/day/max	1	158 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/bme/day/min	1	158 bytes	N.A	3 months ago
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/bme/hour/avg	25	711 bytes	3 months ago	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/bme/hour/max	25	711 bytes	3 months ago	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/bme/hour/min	25	711 bytes	3 months ago	3 months ago

eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/ds18/day/avg	1	159 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/ds18/day/max	1	159 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/ds18/day/min	1	159 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/ds18/hour/avg	25	712 bytes	3 months ago	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/ds18/hour/max	25	712 bytes	3 months ago	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/ds18/hour/min	25	712 bytes	3 months ago	3 months ago

eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/xp/day/avg	1	157 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/xp/day/max	1	157 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/xp/day/min	1	157 bytes	N.A	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/xp/hour/avg	25	710 bytes	3 months ago	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/xp/hour/max	25	710 bytes	3 months ago	3 months ago	
eGeoffrey/sensors/module-out/ourstreet/garden/weatherstation/sensor/temp/xp/hour/min	25	710 bytes	3 months ago	3 months ago	

eGeoffrey/sensors/myplace/myhouse/roosendaal/temperature	495	41.44 Kb	5 days ago	49 minutes ago	3.9
eGeoffrey/sensors/myplace/myhouse/roosendaal/temperature/day/avg	109	2.59 Kb	3 months ago	15 hours ago	3.3
eGeoffrey/sensors/myplace/myhouse/roosendaal/temperature/day/max	109	2.61 Kb	3 months ago	15 hours ago	3.8
eGeoffrey/sensors/myplace/myhouse/roosendaal/temperature/day/min	109	2.57 Kb	3 months ago	15 hours ago	2.3
eGeoffrey/sensors/myplace/myhouse/roosendaal/temperature/hour/avg	134	11.52 Kb	5 days ago	69 minutes ago	3.8
eGeoffrey/sensors/myplace/myhouse/roosendaal/temperature/hour/max	134	11.52 Kb	5 days ago	69 minutes ago	3.9
eGeoffrey/sensors/myplace/myhouse/roosendaal/temperature/hour/min	134	11.52 Kb	5 days ago	69 minutes ago	3.7

**Comment by user2684** [comment]
Ok so basically for having the ability to zoom in and out you should have a timespan of data large enough for not fitting the timeframe presented. This happens only with daily aggregations. myplace/myhouse/roosendaal/temperature seems to be a good one since spanning over 3 months, the others apparently not. Are you having problems with this sensor or others? Sorry, I may have missed this bit. Thanks

**Comment by eporocrail** [comment]
All sensors are on-line for the same period.
The difference is that the first three deliver local data and the last one delivers data from the weather service.
But again, on-line during exactly the same period.

**Comment by user2684** [comment]
Understood. would you mind sharing also the configuration of the chart posted in the first post (from the advanced editor). I want to cross your configuration with the information from the database you share a while ago to see if there is any issue there. Thanks!

**Comment by eporocrail** [comment]
- temperature: []
- ' ':
    - sensors:
        - out/myplace/garden/wthr/sr/tmp/ds18
        - out/myplace/garden/wthr/sr/tmp/bme
        - out/myplace/garden/wthr/sr/tmp/xp
        - myplace/myhouse/roosendaal/temperature
      size: 12
      no_range: false
      widget: timeline
      title: '<p style="text-align:center">overview temperature sensors</p>'
- '':
    - widget: value
      title: '<p style="color:olive;text-align:center">ds18</p>'
      color: olive
      size: 2
      sensor: out/myplace/garden/wthr/sr/tmp/ds18
      icon: thermometer-half
    - size: 2
      widget: value
      title: '<p style="color:olive;text-align:center">bme</p>'
      color: olive
      offset: 1
      sensor: out/myplace/garden/wthr/sr/tmp/bme
      icon: thermometer-half
    - size: 2
      widget: value
      title: '<p style="color:olive;text-align:center">xp</p>'
      color: olive
      offset: 1
      sensor: out/myplace/garden/wthr/sr/tmp/xp
      icon: thermometer-half
    - size: 2
      widget: value
      title: '<p style="color:olive;text-align:center">roosendaal</p>'
      color: olive
      offset: 1
      sensor: myplace/myhouse/roosendaal/temperature
      icon: thermometer-half
- '':
    - size: 8
      widget: summary
      title: max - min
      color: silver
      sensors:
        - out/myplace/garden/wthr/sr/tmp/ds18
        - out/myplace/garden/wthr/sr/tmp/bme
        - out/myplace/garden/wthr/sr/tmp/xp
        - myplace/myhouse/roosendaal/temperature
      offset: 2
      icon: thermometer-half

**Comment by user2684** [comment]
I don't see any `group_by` in your widget definition meaning the latest values are displayed. Those follows the retention policies set so will not last for months. However, you may wonder why you see just the last 4 hours. 
This is because the displayed timeframe by default is:
- latest values: 4 hours
- group by hour: last_24_hours
- group by day: last_365_days

You can still play with this by providing a "Custom Timeframe" in the timeline widget configuration. The syntax is `last_<number>_<days/hours> `
Makes sense?

**Comment by eporocrail** [comment]
I will report back on this one.

**Comment by eporocrail** [comment]
I did not see a way to define "group_by" in the GUI.
How do I set "group_by" and what are the possibilities?

**Comment by user2684** [comment]
Sorry, group_by maps to "Display Aggregated Data" in the GUI

**Comment by eporocrail** [comment]
I am afraid that I am missing something.
I have no clue where to look for "group_by_maps".
???

**Comment by user2684** [comment]
I realized this concept requires a bit more of explanation so I put together this additional page in the docs website: https://docs.egeoffrey.com/configure/gui/widgets/timeline/. This should detail how the different configuration parameters of the widget wizard are used to display the data. Of course let me know if it is still not clear enough. Thanks!

**Comment by eporocrail** [comment]
It is working now. Thanks.

**Comment by user2684** [comment]
Great thanks, hope the detailed explanation helped a bit
